In [ ]:
import numpy as np #np as name or variable of numpy

In [ ]:
s = np.array(1.2) #this is a scalar
print(s)


1.2


In [ ]:
v = np.array([5, 7, 8, 0.5])
print(v)

[5.  7.  8.  0.5]


In [ ]:
v1 = np.array([0,1])
v2 = np.array([1,0])
v3 = np.array([1,1])

print(v1, v2, v3)

[0 1] [1 0] [1 1]


In [ ]:
M = np.array([v1, v2, v3])

print(M)

[[0 1]
 [1 0]
 [1 1]]


In [ ]:
A = np.array([
              [1,2,3],
              [2,4,1],
              [2,2,8]
])

print(A)

[[1 2 3]
 [2 4 1]
 [2 2 8]]


In [ ]:
M1 = np.array([
               [1,0],
               [1,0]
])

M2 = np.array([
               [1,0],
               [0,1]
])

M3 = np.array([
               [2,0],
               [1,1]
])




In [ ]:
tau = np.array([M1,M2,M3])

print(tau)

[[[1 0]
  [1 0]]

 [[1 0]
  [0 1]]

 [[2 0]
  [1 1]]]


Describing Linear identities

In [ ]:
tau.size #variable.size

12

In [ ]:
##shape
tau.shape

(3, 2, 2)

Operations of Vectors



In [ ]:
#Operations of Vectors

a1 = np.array([0,2])
a2 = np.array([2,3])

a3 = a1 / a2

print(a3)

[0.         0.66666667]


In [ ]:
a2**a1

array([1, 9])

In [ ]:
b1 = np.array([1,2])
b2 = np.array([3,2])

np.inner(b1,b2)
#b1@b2 same same^^

7

In [ ]:
weights = np.array([0.3,0.3,0.4])
grades = np.array([80,88,90])

np.inner(weights,grades)

86.4

Matrices

In [ ]:
B = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
])

#Row
B[0]

array([1, 2, 3])

In [ ]:
#all
B[]

array([1, 4, 7])

In [ ]:
B[:,0]@B[:,2]

90

Kinds of Matrices

In [ ]:
#Rows --> shape(1,m)

row = np.array([[1,2,3]])
row.shape

(1, 3)

In [ ]:
#Column --> shape(n,1)

col = np.array([
                [1],
                [2],
                [3]
])
col.shape

(3, 1)

In [ ]:
tau.ndim #dimension

3

In [ ]:
X = np.array([
              [1,0,0],
              [2,1,0.5],
              [3,1,0.5]
])

X.sort


In [ ]:
##Square n = m

In [ ]:
#Ones = all elements are 1
n, m = 2,3
ones = np.ones((n,m))
ones



array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Zeros = all elements are 0
n, m = 2,3
zeros = np.zeros((n,m))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#full
full = np.full((n,m),5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
#Identity Matrix
#I = np.eye(3)
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Diagonal Matrix
d = np.diag([1,2,3])
print(d)
#Trace
#trace_of_X = np.diag(X).sum()
#trace_of_X

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
#Scalar
scalarm = np.diag([2,2,2])
scalarm = 2*np.eye(3)
scalarm

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

Matrix Operations

In [ ]:
#Element wise operations
A = np.array([
              [2,3],
              [2,1]
])
B = np.array([
              [1,1],
              [-1,2]
])

A-B
A+B
A*B
A/B
A**B

In [ ]:
#Matrix Algebra
#Dot Product
A@B

array([[30, 36, 42],
       [25, 32, 39],
       [66, 78, 90]])

In [ ]:
C = np.array([2,2],[2,1])
D = np.array([3],[3],[3])
C@D #error

TypeError: ignored